services:
  app:
    build: .
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=development
      - PORT=6000
      - MONGO_URI=mongodb://mongo:27017/event-management
      - JWT_SECRET=event-management-jwt-secret-key
      - JWT_EXPIRATION_DURATION=4h
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    restart: unless-stopped
    command: npm run dev

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=event-management
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongodb_data:
